title_selectors = ["//meta[@property=\"og:title\"]/@content"]
body_selectors = ["//div[@id='js-article-text']"]
date_selectors = ["//meta[@property=\"article:published_time\"]/@content"]
author_selectors = ["//meta[@name=\"author\"]/@content"]
strip_selectors = [
  "//div[@class='explore-links']",
  "//div[@id='js-article-text']/br[position()=1]",
  "//noscript",
  "//div[@itemprop=\"video\"]",
]
strip_id_or_class = [
  "print-or-mail-links",
  "shareArticles",
  "googleAds",
  "digg-button",
  "article-icon-links-container",
  "clickToEnlarge",
  "articleIconLinksContainer",
  "related-carousel",
  "reader-comments",
  "most-watched",
  "most-read",
]
strip_image_src = []
native_ad_selectors = []
tidy = false
prune = false
autodetect_on_failure = true
single_page_link_selectors = []
next_page_link_selectors = []
replace_strings = [[
  "blkBorder img-share",
  "nothing",
]]

[http_headers]

[[tests]]
  URL = "https://www.dailymail.co.uk/news/article-1375423/Royal-wedding-Texan-billionaire-Joe-Albritton-invited-Prince-Charles.html"
  Contains = []

[[tests]]
  URL = "https://www.dailymail.co.uk/news/article-8850463/Paris-attack-Islamist-terrorist-asked-pupils-point-teacher-beheading-him.html"
  Contains = []
