title_selectors = [
  "//meta[@name='title']/@content",
  "//h1",
]
body_selectors = [
  "//div[contains(@class, 'article-body')]",
  "//div[contains(@class, \"article_body\")]",
  "//body[@id='print_facet']//div[@id='content']",
  "//div[@id='print_facet']//div[@id='body']",
]
date_selectors = [
  "substring-before(//article//div[contains(@class, 'display-date')], ' at ')",
  "//div[contains(@class,'byline')]//span[contains(@class,'published')]/@title",
  "//meta[@name=\"DC.date.issued\"]/@content",
  "//span[contains(@class,\"pb-timestamp\")]",
  "//meta[@name=\"eomportal-lastUpdate\"]/@content",
]
author_selectors = [
  "//article//div[contains(@class, 'byline')]//a[contains(@class, 'author-name-link')]",
  "//meta[@name='DC.creator']/@content",
  "//span[@class=\"pb-byline\"]",
  "//h3[@property='dc.creator']//a[@rel='author']",
  "//a[@class='author-name'][1]",
]
strip_selectors = [
  "//div[@class=\"relative primary-slot padding-top img-border gallery-container photo-wrapper\"]",
  "//div[@id=\"wp-column six end\"]",
  "//div[@id='article-side-rail']",
  "//div[@class=\"module component todays-paper-module curved\"]",
  "//div[@class=\"module component live-qa curved img-border\"]",
  "//div[@class=\"module component newsletter-signup curved\"]",
  "//div[@class=\"module featured-stories component curved img-border\"]",
  "//h3[@property=\"dc.creator\"]",
  "//div[@data-qa=\"article-body-ad\"]",
  "//p[a[@data-qa=\"interstitial-link\"]]",
  "//strong[contains(., 'Read more consumer tech reviews and analysis')]",
  "//strong[contains(., 'Read more tech reviews and advice from')]",
  "//strong[contains(., 'Read more tech advice and analysis from')]",
  "//strong[contains(., 'Read more:')]",
  "//strong[contains(., 'More from PostEverything:')]",
  "//em[contains(., 'You might also like:')]",
  "//svg",
]
strip_id_or_class = [
  "carousel",
  "toolbar",
  "module",
  "tooltip",
  "powa-wrapper",
  "powa-blurb-wrapper",
]
strip_image_src = []
native_ad_selectors = []
tidy = false
prune = false
autodetect_on_failure = true
single_page_link_selectors = ["concat(substring-before(//link[@rel=\"canonical\"]/@href, \"_story.html\"), \"_print.html?noredirect=on\")"]
next_page_link_selectors = []
replace_strings = [[
  ".jpg&amp;w=32\"",
  ".jpg&amp;w=916\"",
]]

[http_headers]
  Cookie = "wp_devicetype=0; rplpwabt4=1; devicetype=0; osfam=0; de=; client_region=0; wp_gdpr=1|1; rplmct=1; washpost_poe=true;"

[[tests]]
  URL = "http://www.washingtonpost.com/world/europe/in-europe-new-fears-of-german-might/2011/10/19/gIQA3baZ7L_story.html?hpid=z1"
  Contains = []

[[tests]]
  URL = "http://www.washingtonpost.com/national/health-science/radical-theory-of-first-americans-places-stone-age-europeans-in-delmarva-20000-years-ago/2012/02/28/gIQA4mriiR_story.html"
  Contains = []

[[tests]]
  URL = "http://www.washingtonpost.com/lifestyle/magazine/the-sorry-fate-of-a-tech-pioneer-halsey-minor-and-historic-virginia-estate-carters-grove/2012/05/30/gJQAwdJG4U_story.html"
  Contains = []

[[tests]]
  URL = "https://www.washingtonpost.com/technology/2020/12/10/amazon-halo-band-review/"
  Contains = []

[[tests]]
  URL = "https://www.washingtonpost.com/posteverything/wp/2015/05/15/take-off-that-fitbit-exercise-alone-wont-make-you-lose-weight/"
  Contains = []

[[tests]]
  URL = "https://www.washingtonpost.com/news/wonk/wp/2015/10/04/what-people-in-1900-thought-the-year-2000-would-look-like/"
  Contains = []
