title_selectors = ["//h1[contains(@class, 'detail-dialog-title')]"]
body_selectors = [
  "//pre[@id='cx-desc-text']",
  "//div[contains(@class, 'overview-tab-right-bar-info')]",
]
date_selectors = []
author_selectors = []
strip_selectors = []
strip_id_or_class = []
strip_image_src = []
native_ad_selectors = []
tidy = false
prune = false
autodetect_on_failure = true
single_page_link_selectors = []
next_page_link_selectors = []
replace_strings = [
  [
  "<noscript>",
  "<div>",
],
  [
  "</noscript>",
  "</div>",
],
]

[http_headers]

[[tests]]
  URL = "https://chrome.google.com/webstore/detail/pnaiinchjaonopoejhknmgjingcnaloc"
  Contains = []
